write some unit test (test some instructions)
CQU-AI/pymips pull request #11
Opened 2019-10-20 16:12 UTC by Musenming

unit test (test_instructions)

2019-10-20 16:15 UTC, Musenming commented
Please don't merge, still working on this PR.

2019-10-21 05:01 UTC, loopyme requested changes

2019-10-21 05:01 UTC, loopyme commented on fengyong/instructions.py
> +# def sra_(rd, rt, shamt)f
please remove this

2019-10-21 06:54 UTC, loopyme commented
Hi, @musenming .To let us pull your changes, please solve the conflicts and merge [this PR](https://github.com/musenming/pymips/pull/1) to active Travis-CI in you fork.

2019-10-21 09:28 UTC, loopyme commented
Move to #17

2019-10-21 09:28 UTC, closed without merging